image: node:22

stages:
    - build
    - test
    - publish

cache:
    key: "$CI_PIPELINE_IID"
    paths:
        - dist/
        - node_modules/

build:
    stage: build
    script:
        - npm install
        - npm run build

test:
    stage: test
    script:
        - npm install
        - npm test

publish:
    stage: publish
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
        - npm publish --access public --verbose
    rules:
        - if: $CI_COMMIT_TAG =~ /^release\/\d/
